#ifndef QTPROPERTYBROWSERGLOBAL_H
#define QTPROPERTYBROWSERGLOBAL_H
#include <memory>

#ifndef QT_QTPROPERTYBROWSER_EXPORT
#if defined(QT_QTPROPERTYBROWSER_MAKE_LIB)  // 定义此宏将构建library
#define QT_QTPROPERTYBROWSER_EXPORT Q_DECL_EXPORT
#else
#define QT_QTPROPERTYBROWSER_EXPORT Q_DECL_IMPORT
#endif
#endif

#ifndef QT_QTPROPERTYBROWSER_EXPORT
#define QT_QTPROPERTYBROWSER_EXPORT
#endif



#endif  // SARIBBONGLOBAL_H
